# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net


trigger:
- master

strategy:
  matrix:
      x64-release:
          buildPlatform: x64
          buildConfiguration: release
      x64-debug:
          buildPlatform: x64
          buildConfiguration: debug
      x86-release:
          buildPlatform: x86
          buildConfiguration: release
      x86-debug:        
          buildPlatform: x86
          buildConfiguration: debug
      x64-release_VSAWAIT:
          buildPlatform: x64
          buildConfiguration: Release_VSAWAIT
      x64-debug_VSAWAIT:
          buildPlatform: x64
          buildConfiguration: Debug_VSAWAIT
      x86-release_VSAWAIT:
          buildPlatform: x86
          buildConfiguration: Release_VSAWAIT
      x86-debug_VSAWAIT:        
          buildPlatform: x86
          buildConfiguration: Debug_VSAWAIT

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: $(buildPlatform)
  buildConfiguration: $(buildConfiguration)

steps:
- script: |
    vcpkg install gtest:$(buildPlatform)-windows
    vcpkg integrate install
  displayName: vcpkg

- task: NuGetToolInstaller@0
  displayName: 'Nuget - Install'

- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestPreRelease'
    
- task: NuGetCommand@2
  displayName: 'Nuget - Restore Packages'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  displayName: 'Google Test  - run tests'
  inputs:
    script: '$(Build.SourcesDirectory)\$(BuildPlatform)\$(BuildConfiguration)\RStein.AsyncCpp.Test.exe --gtest_output="xml:$(Build.SourcesDirectory)\$(BuildPlatform)\$(BuildConfiguration)\RStein.AsyncCpp.Test.xml"'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/RStein.AsyncCpp.Test.xml'

# - task: VSTest@2
#   inputs:
#     testSelector: 'testAssemblies'
#     testAssemblyVer2: '**\RStein.AsyncCpp.Test.exe'
#     searchFolder: '$(System.DefaultWorkingDirectory)'
# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
    
# - task: CopyFiles@2
#   inputs:
#     Contents: '**\$(BuildConfiguration)\**\?(*.exe|*.dll|*.pdb)'
#     TargetFolder: 